global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
  retrofit_generator:
    runs_before:
      - riverpod_generator

targets:
  $default:
    builders:
      freezed:
        options:
          format: false