arb-dir: lib/l10n
template-arb-file: app_it.arb
output-dir: lib/l10n/gen_l10n
output-localization-file: app_localizations.dart
preferred-supported-locales: it
synthetic-package: false
nullable-getter: false
# untranslated-messages-file: desiredFileName.txt