name: 🐛 Bug Report
description: 🐞 Segnala un bug da risolvere al più presto
title: "[BUG]: "

labels: ["bug"]
projects: ["Spook-IT/7"]
assignees: ["dariowskii"]
type: "bug"

body:
  - type: textarea
    id: what-happened
    attributes:
      label: 🛰️ **Cosa è successo?**
      description: Descrivi in modo dettagliato il bug
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: 🖥️ **OS**
      description: Su quale sistema operativo hai riscontrato il bug?
      options:
        - Android
        - Apple
        - Entrambi
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: 🔄 **Che versione?**
      description: e.g. Android 14 or iOS 18.3.2
    validations:
      required: true  
  - type: input
    id: version
    attributes:
      label: 🔢 **Versione App**
      description: Che versione dell'app stai utilizzando? (La puoi trovare in Impostazioni > Informazioni)
      placeholder: e.g. v0.1.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 📸 **Screenshots o logs**
      description: Allega eventuali screenshot o log del bug