name: 🌟 Feature
description: 💡 Inserisci una nuova feature nel progetto
title: "[Feature]: "

labels: ["enhancement"]
projects: ["Spook-IT/7"]
assignees: ["dariowskii"]

body:
  - type: textarea
    id: feature-description
    attributes:
      label: 📝 **Descrizione**
      description: 📖 Descrivi la feature in modo dettagliato, allegando eventualmente immagini e impostando una checklist
    validations:
      required: true